user  nginx;
worker_processes     auto;
worker_rlimit_nofile 65535;
pid /var/run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    multi_accept       on;
    worker_connections 65535;
}

http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    log_not_found          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_max_body_size   320M;

    include                mime.types;
    default_type           application/octet-stream;

    log_format json escape=json '{ "@timestamp": "$time_iso8601", '
        '"remote_addr": "$http_x_forwarded_for", '
        '"body_bytes_sent": "$body_bytes_sent", '
        '"status": $status, '
        '"request": "$request", '
        '"url": "$uri", '
        '"request_method": "$request_method", '
        '"postdata": "$request_body", '
        '"response_time": $upstream_response_time, '
        '"http_referrer": "$http_referer", '
        '"http_user_agent": "$http_user_agent", '
        '"x-request-id": "$requestid", '
        '"request_id": "$request_id"};';

    map $http_x_request_id $requestid {
        default $http_x_request_id;
        "" $request_id;
    }

    include /etc/nginx/conf.d/*.conf;
}
